version: "3.8"

services:
  postgres1:
    image: postgres:latest
    container_name: postgres1
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres2:
    image: postgres:latest
    container_name: postgres2
    restart: always
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  postgres3:
    image: postgres:latest
    container_name: postgres3
    restart: always
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    ports:
      - "5434:5432"
    volumes:
      - postgres3_data:/var/lib/postgresql/data

volumes:
  postgres1_data:
  postgres2_data:
  postgres3_data:
