apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discord
spec:
  project: default
  source:
    repoURL: https://github.com/helloankitpandey/Discord.git
    path: kubernetes
    targetRevision: anand
  destination:
    server: https://kubernetes.default.svc
    namespace: discord
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true