apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
  type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWUK #username
  POSTGRES_PASSWORD: cGFzc3dvcmQK #password
  POSTGRES_DB: ZGlzY29yZAo= #discord