apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-auth-deployment
  namespace: discord 

spec:
  replicas: 3
  selector:
    matchLabels:
      app: discord-auth
  template: 
    metadata:
      labels:
        app: discord-auth
    spec:
      containers:
        - name: discord-auth
          image: dubeyanand/auth-discord:01
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgresql://user1:password1@postgres:5432/discord"
            - name: NATS_URI
              value: "nats://45.8.133.227:4222"
            - name: JWT_SECRET
              value: "your-jwt-secret"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
            