apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discord-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "tws.com"
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: discord-auth-service
            port:
              number: 3000
      