apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
  namespace: discord
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
